import {
  CLAUDE_PORTRAIT,
  PHILIPPE_PORTRAIT,
  RAPHAEL_PORTRAIT,
} from './portraits.js';

/**
 * Who worked on this, for the screen hidden behind seven presses on the logo.
 *
 * French only, and deliberately so. The captions run on puns — "aspirateur"
 * against "inspirateur", "con sultan" out of "consultant", a chain of
 * electrical senses of "branché", "au courant" and "pile" — and every English
 * rendering of them was a translation of a joke rather than a joke. The rest
 * of the game is bilingual; this page is a private one, in the language it was
 * written in.
 *
 * The heading changes with the face rather than standing above all three: each
 * of them did a different job, and "réalisé / motivé / codé" says so in one
 * word where a shared title would need a sentence.
 *
 * One caption per person and no separate name line: the captions were written
 * to begin with the name, and printing it twice would read like a form. The
 * name survives as the alt text and on the dots, where it does work.
 *
 * The portraits are data URIs from `portraits.ts`, generated by
 * `scripts/build-portraits.mjs`. They travel inside the bundle because the APK
 * and the single HTML file have nowhere to fetch from.
 */
export interface Credit {
  /** For alt text and the dot labels, not for display. */
  name: string;
  /** What this person did, shown above their face. */
  heading: string;
  caption: string;
  photo: string;
}

export const CREDITS: Credit[] = [
  {
    name: 'Philippe',
    heading: 'Réalisé par',
    caption:
      'Philippe, le très sérieux développeur de l’application en 1986 et en 2026. Entre les deux… rien.',
    photo: PHILIPPE_PORTRAIT,
  },
  {
    name: 'Raphaël',
    heading: 'Motivé par',
    caption:
      'Raphaël, le moins sérieux instigateur, inspirateur, aspirateur, consultant, con sultan de l’application et de son barème des points.',
    photo: RAPHAEL_PORTRAIT,
  },
  {
    name: 'Claude',
    heading: 'Codé par',
    caption:
      'Claude, développeur branché… trop branché même. Au courant des dernières technologies… très au courant. Très dynamique, une vraie pile électrique.',
    photo: CLAUDE_PORTRAIT,
  },
];

/** The one word of chrome the page keeps. */
export const CREDITS_BACK = 'Retour';

/** The next face, wrapping round. */
export function nextCredit(index: number, total: number = CREDITS.length): number {
  if (total <= 0) return 0;
  return (index + 1) % total;
}

/** The previous face, wrapping round the other way. */
export function prevCredit(index: number, total: number = CREDITS.length): number {
  if (total <= 0) return 0;
  return (index - 1 + total) % total;
}

/**
 * How far a finger must travel before it counts as a swipe.
 *
 * Short enough to be comfortable on a phone, long enough that the wobble in a
 * tap never reads as a flick.
 */
export const SWIPE_MIN_PX = 40;

export type Swipe = 'next' | 'previous' | null;

/**
 * What a drag meant, from how far it went in each direction.
 *
 * Two things have to be told apart from a swipe: a tap, which barely moves,
 * and a scroll, which moves further down the screen than across it. Requiring
 * the horizontal travel to beat the vertical is what stops a thumb sliding
 * down the page from flicking through the credits on its way past.
 *
 * A finger moving left drags the next face into view, the way a page does.
 */
export function swipeFrom(dx: number, dy: number): Swipe {
  if (Math.abs(dx) < SWIPE_MIN_PX) return null;
  if (Math.abs(dx) <= Math.abs(dy)) return null;
  return dx < 0 ? 'next' : 'previous';
}
